server:
  port: 8000
  contextPath: /documentservice
  ssl:
    enabled: true
    key-store: classpath:keystore.jks
    key-store-password: bocobomc
    key-password: bocobomc
    keyAlias: itosi
    trust-store: classpath:keystore.jks
    trust-store-password: bocobomc
    trust-store-type: jks
security:
  oauth2:
    resource:
      userInfoUri: https://localhost:9999/api/user
multipart:
  max-file-size: 100MB
  max-request-size: 100MB
spring:
  thymeleaf:
    cache: false
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:memdb
    username: sa
    password: null
    platform: h2
    initialize: true
  cloud:
    config:
      enabled: true
      uri: http://localhost:8888
  boot:
    admin:
      url: http://localhost:8762
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
ribbon:
  eureka:
    enabled: true